// <auto-generated />
using System;
using Api.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Api.Data.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20210928121348_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Api.Domain.Entities.AddressEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("character varying(90)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Complement")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ZipCode")
                        .HasMaxLength(8)
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Api.Domain.Entities.ClientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cpf_Cnpj")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("character varying(90)");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Api.Domain.Entities.ImagePathEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ImagePath");

                    b.HasIndex("ProductId");

                    b.ToTable("ImagePath");
                });

            modelBuilder.Entity("Api.Domain.Entities.PhoneEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SocialPhone")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Phone");
                });

            modelBuilder.Entity("Api.Domain.Entities.ProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("boolean");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<double>("PriceOff")
                        .HasColumnType("double precision");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("character varying(90)");

                    b.Property<Guid>("ProductTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.HasIndex("ProductName")
                        .IsUnique();

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Api.Domain.Entities.ProductTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ProductType")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductType");

                    b.ToTable("ProductType");
                });

            modelBuilder.Entity("Api.Domain.Entities.StatesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Sigla");

                    b.ToTable("State");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22ffbd18-cdb9-45cc-97b0-51e97700bf71"),
                            CreatedAt = new DateTime(2021, 9, 28, 12, 13, 47, 623, DateTimeKind.Utc).AddTicks(3680),
                            Sigla = "AC",
                            StateName = "Acre"
                        },
                        new
                        {
                            Id = new Guid("7cc33300-586e-4be8-9a4d-bd9f01ee9ad8"),
                            CreatedAt = new DateTime(2021, 9, 28, 12, 13, 47, 623, DateTimeKind.Utc).AddTicks(7180),
                            Sigla = "AL",
                            StateName = "Alagoas"
                        },
                        new
                        {
                            Id = new Guid("cb9e6888-2094-45ee-bc44-37ced33c693a"),
                            CreatedAt = new DateTime(2021, 9, 28, 12, 13, 47, 623, DateTimeKind.Utc).AddTicks(7190),
                            Sigla = "AM",
                            StateName = "Amazonas"
                        },
                        new
                        {
                            Id = new Guid("409b9043-88a4-4e86-9cca-ca1fb0d0d35b"),
                            CreatedAt = new DateTime(2021, 9, 28, 12, 13, 47, 623, DateTimeKind.Utc).AddTicks(7190),
                            Sigla = "AP",
                            StateName = "Amapá"
                        },
                        new
                        {
                            Id = new Guid("5abca453-d035-4766-a81b-9f73d683a54b"),
                            CreatedAt = new DateTime(2021, 9, 28, 12, 13, 47, 623, DateTimeKind.Utc).AddTicks(7200),
                            Sigla = "BA",
                            StateName = "Bahia"
                        },
                        new
                        {
                            Id = new Guid("5ff1b59e-11e7-414d-827e-609dc5f7e333"),
                            CreatedAt = new DateTime(2021, 9, 28, 12, 13, 47, 623, DateTimeKind.Utc).AddTicks(7200),
                            Sigla = "CE",
                            StateName = "Ceará"
                        },
                        new
                        {
                            Id = new Guid("bd08208b-bfca-47a4-9cd0-37e4e1fa5006"),
                            CreatedAt = new DateTime(2021, 9, 28, 12, 13, 47, 623, DateTimeKind.Utc).AddTicks(7210),
                            Sigla = "DF",
                            StateName = "Distrito Federal"
                        },
                        new
                        {
                            Id = new Guid("c623f804-37d8-4a19-92c1-67fd162862e6"),
                            CreatedAt = new DateTime(2021, 9, 28, 12, 13, 47, 623, DateTimeKind.Utc).AddTicks(7210),
                            Sigla = "ES",
                            StateName = "Espírito Santo"
                        },
                        new
                        {
                            Id = new Guid("837a64d3-c649-4172-a4e0-2b20d3c85224"),
                            CreatedAt = new DateTime(2021, 9, 28, 12, 13, 47, 623, DateTimeKind.Utc).AddTicks(7210),
                            Sigla = "GO",
                            StateName = "Goiás"
                        },
                        new
                        {
                            Id = new Guid("57a9e9f7-9aea-40fe-a783-65d4feb59fa8"),
                            CreatedAt = new DateTime(2021, 9, 28, 12, 13, 47, 623, DateTimeKind.Utc).AddTicks(7220),
                            Sigla = "MA",
                            StateName = "Maranhão"
                        },
                        new
                        {
                            Id = new Guid("27f7a92b-1979-4e1c-be9d-cd3bb73552a8"),
                            CreatedAt = new DateTime(2021, 9, 28, 12, 13, 47, 623, DateTimeKind.Utc).AddTicks(7220),
                            Sigla = "MG",
                            StateName = "Minas Gerais"
                        },
                        new
                        {
                            Id = new Guid("3739969c-fd8a-4411-9faa-3f718ca85e70"),
                            CreatedAt = new DateTime(2021, 9, 28, 12, 13, 47, 623, DateTimeKind.Utc).AddTicks(7220),
                            Sigla = "MS",
                            StateName = "Mato Grosso do Sul"
                        },
                        new
                        {
                            Id = new Guid("29eec4d3-b061-427d-894f-7f0fecc7f65f"),
                            CreatedAt = new DateTime(2021, 9, 28, 12, 13, 47, 623, DateTimeKind.Utc).AddTicks(7230),
                            Sigla = "MT",
                            StateName = "Mato Grosso"
                        },
                        new
                        {
                            Id = new Guid("8411e9bc-d3b2-4a9b-9d15-78633d64fc7c"),
                            CreatedAt = new DateTime(2021, 9, 28, 12, 13, 47, 623, DateTimeKind.Utc).AddTicks(7230),
                            Sigla = "PA",
                            StateName = "Pará"
                        },
                        new
                        {
                            Id = new Guid("1109ab04-a3a5-476e-bdce-6c3e2c2badee"),
                            CreatedAt = new DateTime(2021, 9, 28, 12, 13, 47, 623, DateTimeKind.Utc).AddTicks(7230),
                            Sigla = "PB",
                            StateName = "Paraíba"
                        },
                        new
                        {
                            Id = new Guid("ad5969bd-82dc-4e23-ace2-d8495935dd2e"),
                            CreatedAt = new DateTime(2021, 9, 28, 12, 13, 47, 623, DateTimeKind.Utc).AddTicks(7240),
                            Sigla = "PE",
                            StateName = "Pernambuco"
                        },
                        new
                        {
                            Id = new Guid("f85a6cd0-2237-46b1-a103-d3494ab27774"),
                            CreatedAt = new DateTime(2021, 9, 28, 12, 13, 47, 623, DateTimeKind.Utc).AddTicks(7240),
                            Sigla = "PI",
                            StateName = "Piauí"
                        },
                        new
                        {
                            Id = new Guid("1dd25850-6270-48f8-8b77-2f0f079480ab"),
                            CreatedAt = new DateTime(2021, 9, 28, 12, 13, 47, 623, DateTimeKind.Utc).AddTicks(7250),
                            Sigla = "PR",
                            StateName = "Paraná"
                        },
                        new
                        {
                            Id = new Guid("43a0f783-a042-4c46-8688-5dd4489d2ec7"),
                            CreatedAt = new DateTime(2021, 9, 28, 12, 13, 47, 623, DateTimeKind.Utc).AddTicks(7250),
                            Sigla = "RJ",
                            StateName = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = new Guid("542668d1-50ba-4fca-bbc3-4b27af108ea3"),
                            CreatedAt = new DateTime(2021, 9, 28, 12, 13, 47, 623, DateTimeKind.Utc).AddTicks(7250),
                            Sigla = "RN",
                            StateName = "Rio Grande do Norte"
                        },
                        new
                        {
                            Id = new Guid("924e7250-7d39-4e8b-86bf-a8578cbf4002"),
                            CreatedAt = new DateTime(2021, 9, 28, 12, 13, 47, 623, DateTimeKind.Utc).AddTicks(7260),
                            Sigla = "RO",
                            StateName = "Rondônia"
                        },
                        new
                        {
                            Id = new Guid("9fd3c97a-dc68-4af5-bc65-694cca0f2869"),
                            CreatedAt = new DateTime(2021, 9, 28, 12, 13, 47, 623, DateTimeKind.Utc).AddTicks(7260),
                            Sigla = "RR",
                            StateName = "Roraima"
                        },
                        new
                        {
                            Id = new Guid("88970a32-3a2a-4a95-8a18-2087b65f59d1"),
                            CreatedAt = new DateTime(2021, 9, 28, 12, 13, 47, 623, DateTimeKind.Utc).AddTicks(7260),
                            Sigla = "RS",
                            StateName = "Rio Grande do Sul"
                        },
                        new
                        {
                            Id = new Guid("b81f95e0-f226-4afd-9763-290001637ed4"),
                            CreatedAt = new DateTime(2021, 9, 28, 12, 13, 47, 623, DateTimeKind.Utc).AddTicks(7270),
                            Sigla = "SC",
                            StateName = "Santa Catarina"
                        },
                        new
                        {
                            Id = new Guid("fe8ca516-034f-4249-bc5a-31c85ef220ea"),
                            CreatedAt = new DateTime(2021, 9, 28, 12, 13, 47, 623, DateTimeKind.Utc).AddTicks(7270),
                            Sigla = "SE",
                            StateName = "Sergipe"
                        },
                        new
                        {
                            Id = new Guid("e7e416de-477c-4fa3-a541-b5af5f35ccf6"),
                            CreatedAt = new DateTime(2021, 9, 28, 12, 13, 47, 623, DateTimeKind.Utc).AddTicks(7270),
                            Sigla = "SP",
                            StateName = "São Paulo"
                        },
                        new
                        {
                            Id = new Guid("971dcb34-86ea-4f92-989d-064f749e23c9"),
                            CreatedAt = new DateTime(2021, 9, 28, 12, 13, 47, 623, DateTimeKind.Utc).AddTicks(7280),
                            Sigla = "TO",
                            StateName = "Tocantins"
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("character varying(90)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7d64bfd1-547c-45ef-9a3d-4579acb07bd5"),
                            CreatedAt = new DateTime(2021, 9, 28, 9, 13, 47, 625, DateTimeKind.Local).AddTicks(5660),
                            Email = "junior.saint@gmail.com",
                            IsActive = true,
                            Password = "123456",
                            UpdatedAt = new DateTime(2021, 9, 28, 9, 13, 47, 646, DateTimeKind.Local).AddTicks(510),
                            UserName = "Junior",
                            UserType = "administrator"
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.AddressEntity", b =>
                {
                    b.HasOne("Api.Domain.Entities.ClientEntity", "Client")
                        .WithMany("Addresses")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Api.Domain.Entities.ImagePathEntity", b =>
                {
                    b.HasOne("Api.Domain.Entities.ProductEntity", "Product")
                        .WithMany("ImagePaths")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Api.Domain.Entities.PhoneEntity", b =>
                {
                    b.HasOne("Api.Domain.Entities.ClientEntity", "Client")
                        .WithMany("Phones")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Api.Domain.Entities.ProductEntity", b =>
                {
                    b.HasOne("Api.Domain.Entities.ProductTypeEntity", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("Api.Domain.Entities.ClientEntity", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Phones");
                });

            modelBuilder.Entity("Api.Domain.Entities.ProductEntity", b =>
                {
                    b.Navigation("ImagePaths");
                });

            modelBuilder.Entity("Api.Domain.Entities.ProductTypeEntity", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
